stages:
  - test

default:               # Add a default section to define the `image` keyword's default value
  image: agostini01/soda-bookworm:v19.02

.standard-rules:       # Make a hidden job to hold the common rules
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

tflite-test:
  stage: test
  image: agostini01/soda-bookworm:v19.02
  extends:
    - .standard-rules  # Reuse the configuration in `.standard-rules` here
  dependencies: []
  script:
    - cd tests
    - sh tflite_tests.sh
